version: "3.8"

#
# A overriding compose file for running lambda along with alpha & zero
#
services:

  alpha:
    environment:
      DGRAPH_ALPHA_LIMIT: mutations-nquad=500
      DGRAPH_ALPHA_GRAPHQL: lambda-url=http://lambda:8686/graphql-worker
    command: >
      dgraph alpha --my=alpha:7080 --zero=zero:5080
        --security whitelist=0.0.0.0/0
        --logtostderr -v=2
        --telemetry sentry=false
  lambda: 
    image: dgraph/dgraph-lambda:latest
    volumes:
      - ./scripts/script.js:/app/script/script.js:ro
    environment:
      - DGRAPH_URL=http://host.docker.internal:8080
      - MAX_MEMORY_LIMIT=256M
    ports:
      - 8686:8686
  
