mutation Mutation {
  updateTurbine(
    input: { 
      set: { 
        number_of_blades: 4
      }, 
      filter: { 
        id: { 
          eq: "WT003" 
        } 
      }
    }
  ) {
    numUids
    turbine {
      id
      number_of_blades
    }
  }
}
