query ExampleQuery {
  queryEntityNode {
    id
    connections {
      connectionType
      ... on EntityValConnectionNode {
        connectionType
        entityNode {
          id
        }
        valueNode {
          id
          ... on StringValueNode {
            value
          }
        }
      }
    }
  }
}